---
title: "Clustering"
author: "Peter Aspholm"
date: "4/26/2022"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo=TRUE, eval=FALSE)

library(readr)
library(ggplot2)
library(dplyr)
library(tidymodels)
library(rvest)
tidymodels_prefer()
library(mosaic)
library(glmnet)
```


```{r, eval=FALSE}
pitching = read.csv("stats.csv")


pitching_clean = pitching %>%
  select(c(1,2,7,34,35,36,118:138)) %>%
  drop_na() %>%
  select(-c(1,2)) %>%
  select(!contains("formatted"))

# save(pitching_clean, file = "pitching_clean.rdata")

```

```{r}
pitching_cluster <- function(k){
    # Perform clustering
    kclust <- kmeans(scale(pitching_clean), centers = k)

    # Return the total within-cluster sum of squares
    return(kclust$tot.withinss)
}

tibble(
    k = 1:15,
    tot_wc_ss = purrr::map_dbl(1:15, pitching_cluster)
) %>% 
    ggplot(aes(x = k, y = tot_wc_ss)) +
    geom_point() + 
    labs(x = "Number of clusters",y = 'Total within-cluster sum of squares') + 
    theme_classic()
```

